// Generated by CoffeeScript 1.12.7
(function() {
  var getItem, link_regex, ofo_init, ofo_server, ofo_showCode;

  ofo_server = 'https://easy-mock.com/mock/594b9f658ac26d795f4387ac/bike/ofo';

  link_regex = /[a-zA-z]+:\/\/[^\s]*/;

  $(document).ready(function() {
    $(document.body).pullToRefresh();
    ofo_init();
  });

  $(document.body).on('pull-to-refresh', function() {
    ofo_init();
  });

  ofo_init = function() {
    $('#ofo-items').html('');
    $('#ofo-items').hide();
    $.getJSON(ofo_server, function(ofo_data) {
      var ofos_html;
      ofos_html = '';
      $.each(ofo_data, function(i, ofo_item) {
        var ofo_html;
        ofo_html = getItem(ofo_item['desc'], ofo_item['money'], ofo_item['city'], ofo_item['code'], ofo_item['time']);
        ofos_html += ofo_html;
      });
      $('#ofo-items').html(ofos_html);
      $('#loading').hide();
      $('#ofo-items').show();
      $.toptip('加载成功', 1000, 'success');
      $(document.body).pullToRefreshDone();
      $('.showCode').click(function() {
        ofo_showCode(decodeURIComponent($(this).attr('code')), $(this).attr('money'), $(this).attr('city'), $(this).attr('timeout'));
      });
    });
  };

  ofo_showCode = function(code, money, city, timeout) {
    if (link_regex.test(code)) {
      $.confirm({
        title: '即将跳转到',
        text: code,
        onOK: function() {
          location.href = code;
        }
      });
    } else {
      $.prompt({
        title: "请复制",
        text: "金额:" + money + "<br>适用地区:" + city + "<br>过期:" + timeout,
        input: "" + code
      });
    }
  };

  getItem = function(title, money, city, code, timeout) {
    var en_code, itemHtml;
    en_code = encodeURIComponent(code);
    itemHtml = '<a class="weui-cell weui-cell_access showCode"' + (" code=\"" + en_code + "\" city=\"" + city + "\"") + (" money=\"" + money + "\" timeout=\"" + timeout + "\" href=\"javascript:void(0);") + ("\"><div class=\"weui-cell__bd\"><p>" + title) + "</p></div><div class=\"weui-cell__ft\"></div></a>";
    return itemHtml;
  };

}).call(this);
