// Generated by CoffeeScript 1.12.7
(function() {
  var getItem, link_regex, other_init, other_server, other_showCode;

  other_server = 'https://easy-mock.com/mock/594b9f658ac26d795f4387ac/bike/other';

  link_regex = /[a-zA-z]+:\/\/[^\s]*/;

  $(document).ready(function() {
    $(document.body).pullToRefresh();
    other_init();
  });

  $(document.body).on('pull-to-refresh', function() {
    other_init();
  });

  other_init = function() {
    $('#other-items').html('');
    $('#other-items').hide();
    $.getJSON(other_server, function(other_data) {
      var others_html;
      others_html = '';
      $.each(other_data, function(i, other_item) {
        var other_html;
        other_html = getItem(other_item['desc'], other_item['money'], other_item['city'], other_item['code'], other_item['time']);
        others_html += other_html;
      });
      $('#other-items').html(others_html);
      $('#loading').hide();
      $('#other-items').show();
      $.toptip('加载成功', 1000, 'success');
      $(document.body).pullToRefreshDone();
      $('.showCode').click(function() {
        other_showCode(decodeURIComponent($(this).attr('code')), $(this).attr('money'), $(this).attr('city'), $(this).attr('timeout'));
      });
    });
  };

  other_showCode = function(code, money, city, timeout) {
    if (link_regex.test(code)) {
      $.confirm({
        title: '即将跳转到',
        text: code,
        onOK: function() {
          location.href = code;
        }
      });
    } else {
      $.prompt({
        title: "请复制",
        text: "金额:" + money + "<br>适用地区:" + city + "<br>过期:" + timeout,
        input: "" + code
      });
    }
  };

  getItem = function(title, money, city, code, timeout) {
    var en_code, itemHtml;
    en_code = encodeURIComponent(code);
    itemHtml = '<a class="weui-cell weui-cell_access showCode"' + (" code=\"" + en_code + "\" city=\"" + city + "\"") + (" money=\"" + money + "\" timeout=\"" + timeout + "\" href=\"javascript:void(0);") + ("\"><div class=\"weui-cell__bd\"><p>" + title) + "</p></div><div class=\"weui-cell__ft\"></div></a>";
    return itemHtml;
  };

}).call(this);
